### PR TITLE
fix app startup

### PR DESCRIPTION
**Pull request by chinwobble**
- add a placeholder add account dialog
- remove static methods on RootRepository and RootViewModel

### CODE REVIEW

**Comment by Mxchaeltrxn** [comment]
```
class AzureAccount {
  public int AccountId;
  public string ConnectingString;
}

class AwsAccount {
  public int AccountId; 
  public string KeyId;
  public string SecretAccessKey;
  public string Region; // ???
}

class MessagingAccount {
  public int id;
  public int AccountId;
  public int MessagingAccountDataId;
}

class MessagingAccountData {
  public int MessagingAccountDataId;
  public virtual MessagingAccountType Type { get; set; }
  public string DisplayName;

  public MessagingEntity[] Children;
}

messaging entity {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public long ActiveMessages { get; set; }
        public long PoisonMessages { get; set; }
        // todo change to connection id
        public string ConnectionStrings { get; set; }

        public int MessagingAccountDataId;
        public MessagingAccountData MessagingAccountData;
}
```

Every queue should share the same 'messaging account data' fields with a name and active and poison messages. I'm not so sure what the connection string in messaging entity is though. @chinwobble

**Comment by chinwobble** [comment]
so is there any inheritance?

**Comment by Mxchaeltrxn** [comment]
## Entities
```
class AzureServiceBusAccount : MessagingAccount {
  public int Id;
  public string ConnectingString;
}

class AwsAccount : MessagingAccount {
  public int Id; 
  public string KeyId;
  public string SecretAccessKey;
  public string Region; // ???
}

class MessagingAccount {
  public int Id;
  public virtual MessagingAccountType Type { get; set; }
  public string DisplayName;

  public MessagingEntity[] Children;
}

class MessagingEntity {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public long ActiveMessages { get; set; }
        public long PoisonMessages { get; set; }
        // todo change to connection id
        public string ConnectionStrings { get; set; }
}
```

## Repositories
```
class AzureServiceBusRepository : IAccountRepository {

}

class AwsSqsRepository : IAccountRepository {

}

interface IAccountRepository {
  public Task<MessagingAccount> AddAccount()
  public Task<IList<T>> GetQueues()
  public Task<T> DeleteMessage()
  public Task<MessagingAccount> RemoveAccount()
  public Task<MessagingAccount[]> GetAccounts()

  // Extra stuff
  // Add/remove tags and creating and deleting queues
}

class AwsSqsRepository {

}
```

**Comment by chinwobble** [comment]
so would root repository be something like this then
```csharp
class RootRepository
{
    IDictionary<AccountType, IAccountRepository> AccountRepositories { get; }
}

class RootViewModel
{
  async void RemoveAzureAccount(int id)
  {
         // delete an service bus account
         IsLoading = true;
         await RootRepository.AccountRepositories[AccountType.AzureServiceBus].RemoveAccount(id);
         IsLoading = false;
  }
}
```

**Comment by Mxchaeltrxn** [comment]
This looks like it would work. Are we going with this implementation?

**Pull request merged**
